#!/bin/sh

machine=tx53

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp


# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.ethaddr=de:ad:be:ef:00:00
#eth0.netmask=a.b.c.d
#eth0.serverip=a.b.c.d
#eth0.gateway=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=nand
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=nand

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-$machine.$rootfs_type

kernelimage=uImage
#kernelimage=zImage_$machine
#kernelimage=uImage-$machine
#kernelimage=Image-$machine
#kernelimage=Image-$machine.lzo
kernel_part=nand0.kernel

#nfsroot="$serverip:/srv/root"

autoboot_timeout=3

bootargs="console=ttymxc0,115200 panic=1 tx53_base=stkv3 otg_mode=host rootwait video=LVDS-1:800x600MR-32@60"

nand_device=mxc_nand
nand_parts="384k(barebox)ro,128k(bareboxenv),4M(kernel),-(root)"
rootfs_mtdblock_nand=3

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31mtx53:\w\e[0m "
